package com.puii.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.puii.bean.BookListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table booklist.
*/
public class BookListBeanDao extends AbstractDao<BookListBean, String> {

    public static final String TABLENAME = "booklist";

    /**
     * Properties of entity BookListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Add_date = new Property(2, String.class, "add_date", false, "ADD_DATE");
        public final static Property Complete_date = new Property(3, String.class, "complete_date", false, "COMPLETE_DATE");
        public final static Property State = new Property(4, String.class, "state", false, "STATE");
    };


    public BookListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'booklist' (" + //
                "'ID' TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'ADD_DATE' TEXT," + // 2: add_date
                "'COMPLETE_DATE' TEXT," + // 3: complete_date
                "'STATE' TEXT);"); // 4: state
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_booklist_ID ON booklist" +
                " (ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'booklist'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BookListBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String add_date = entity.getAdd_date();
        if (add_date != null) {
            stmt.bindString(3, add_date);
        }
 
        String complete_date = entity.getComplete_date();
        if (complete_date != null) {
            stmt.bindString(4, complete_date);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(5, state);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BookListBean readEntity(Cursor cursor, int offset) {
        BookListBean entity = new BookListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // add_date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // complete_date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // state
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BookListBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAdd_date(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setComplete_date(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setState(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(BookListBean entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(BookListBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
