package com.puii.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table booklist.
 */
public class BookListBean {

    private String id;
    private String name;
    private String add_date;
    private String complete_date;
    private String state;

    public BookListBean() {
    }

    public BookListBean(String id) {
        this.id = id;
    }

    public BookListBean(String id, String name, String add_date, String complete_date, String state) {
        this.id = id;
        this.name = name;
        this.add_date = add_date;
        this.complete_date = complete_date;
        this.state = state;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAdd_date() {
        return add_date;
    }

    public void setAdd_date(String add_date) {
        this.add_date = add_date;
    }

    public String getComplete_date() {
        return complete_date;
    }

    public void setComplete_date(String complete_date) {
        this.complete_date = complete_date;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
