package com.puii.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table pastbooklist.
 */
public class PastBookListBean {

    private String id;
    private String name;
    private String complete_date;

    public PastBookListBean() {
    }

    public PastBookListBean(String id) {
        this.id = id;
    }

    public PastBookListBean(String id, String name, String complete_date) {
        this.id = id;
        this.name = name;
        this.complete_date = complete_date;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getComplete_date() {
        return complete_date;
    }

    public void setComplete_date(String complete_date) {
        this.complete_date = complete_date;
    }

}
