package com.puii.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table feed.
 */
public class PastFeedBean {

    private String id;
    private String name;
    private String buy_date;
    private String plan_id;
    private String book_id;
    private String price;

    public PastFeedBean() {
    }

    public PastFeedBean(String id) {
        this.id = id;
    }

    public PastFeedBean(String id, String name, String buy_date, String plan_id, String book_id, String price) {
        this.id = id;
        this.name = name;
        this.buy_date = buy_date;
        this.plan_id = plan_id;
        this.book_id = book_id;
        this.price = price;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBuy_date() {
        return buy_date;
    }

    public void setBuy_date(String buy_date) {
        this.buy_date = buy_date;
    }

    public String getPlan_id() {
        return plan_id;
    }

    public void setPlan_id(String plan_id) {
        this.plan_id = plan_id;
    }

    public String getBook_id() {
        return book_id;
    }

    public void setBook_id(String book_id) {
        this.book_id = book_id;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

}
