package com.puii.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table yearplan.
 */
public class YearPlanBean {

    private String id;
    private String content;
    private String add_date;
    private String complete_date;
    private String state;

    public YearPlanBean() {
    }

    public YearPlanBean(String id) {
        this.id = id;
    }

    public YearPlanBean(String id, String content, String add_date, String complete_date, String state) {
        this.id = id;
        this.content = content;
        this.add_date = add_date;
        this.complete_date = complete_date;
        this.state = state;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAdd_date() {
        return add_date;
    }

    public void setAdd_date(String add_date) {
        this.add_date = add_date;
    }

    public String getComplete_date() {
        return complete_date;
    }

    public void setComplete_date(String complete_date) {
        this.complete_date = complete_date;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
